const express = require("express");
const cors = require("cors");

const authRoutes = require("../route/auth_route");
const adminRoutes = require("../route/admin_profile.js");
const facultyRoutes = require("../route/facultyprofile_route");
const facultyuploadlink_route = require("../route/facultyuploadlink_route");
const adminsocialmedia_route = require("../route/adminsocialmediamanagement_route");
const admincategorycontrol_route = require("../route/admincategorycontrol_route");
const facultysubmission_route = require("../route/facultysubmission_route");
const payment_route = require("../route/payment_route");
const adminsubmissionqueue_route = require("../route/adminsubmissionqueue_route");
const adminsubmissionview_route = require("../route/adminsubmissionview_route");
const admintempadmin_route = require("../route/admintempadmin_route");
const admindashboard_route = require("../route/admindashboard_route");
const adminfacprofile_route = require("../route/adminfacprofile_route"); 
const mypublication_route = require("../route/mypublication_route");
const notify_route = require("../route/notify_route");
const testrouter_route = require("../route/testrouter");
const app = express();

console.log("authRoutes", typeof authRoutes);
console.log("adminRoutes", typeof adminRoutes);
console.log("facultyRoutes", typeof facultyRoutes);
console.log("facultyuploadlink_route", typeof facultyuploadlink_route);
console.log("adminsocialmedia_route", typeof adminsocialmedia_route);
console.log("admincategorycontrol_route", typeof admincategorycontrol_route);
console.log("facultysubmission_route", typeof facultysubmission_route);
console.log("payment_route", typeof payment_route);
console.log("adminsubmissionqueue_route", typeof adminsubmissionqueue_route);
console.log("adminsubmissionview_route", typeof adminsubmissionview_route);
console.log("admintempadmin_route", typeof admintempadmin_route);
console.log("admindashboard_route", typeof admindashboard_route);
console.log("adminfacprofile_route", typeof adminfacprofile_route);
console.log("mypublication_route", typeof mypublication_route);
console.log("notify_route", typeof notify_route);
app.use(cors());
app.use(express.json());

app.use("/api/auth", authRoutes);
app.use("/api/admin", adminRoutes);
app.use("/api/faculty", facultyRoutes);
app.use("/api/faculty/social-links", facultyuploadlink_route);
app.use("/api/admin/social-links", adminsocialmedia_route);
app.use("/api/admin/category-control", admincategorycontrol_route);
app.use("/api/faculty/submission", facultysubmission_route);
app.use("/api/payment", payment_route);
app.use("/api/admin/submissionqueue", adminsubmissionqueue_route);
app.use("/api/admin/submission/view", adminsubmissionview_route);
app.use("/api/admin/tempadmin", admintempadmin_route);
app.use("/api/admin/dashboard", admindashboard_route);
app.use("/api/admin", adminfacprofile_route); 
app.use("/api",mypublication_route);
app.use("/api/notifications",notify_route);
app.use("/test",testrouter_route);
module.exports = app;